### ISSUE TITLE
保存配置文件路径调整

### ISSUE THREAD

**Issue by VaalaCat** [go-gost/x#10]
在docker中如果使用相对路径会保存到/bin/文件夹，导致持久化失效，虽然可以挂载文件但并不优雅。
这里感觉新增路径参数或保存到读取的配置文件的路径为保存路径比较好

https://github.com/go-gost/x/blob/46db8480faa9fce9676a37f5301bd9a14de58cba/api/config.go#L73

**Comment by ginuerzh** [comment]
已经增加自定义保存路径参数。
